[phases.setup]
nixPkgs = ["nodePackages.npm", "google-chrome", "openssl"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npx prisma migrate deploy", "npm run build"]

[start]
cmd = "npm start"
